package com.leo.service.impl;

import com.leo.model.LeoMessage;
import com.leo.model.NamePwdCookie;
import com.leo.model.OrderDetail;
import com.leo.model.domain.LeoUser;
import com.leo.service.ILeoService;
import com.leo.util.*;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.apache.http.*;
import org.apache.http.client.config.RequestConfig;
import org.apache.http.client.entity.DeflateDecompressingEntity;
import org.apache.http.client.entity.GzipDecompressingEntity;
import org.apache.http.client.methods.CloseableHttpResponse;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.client.utils.URLEncodedUtils;
import org.apache.http.entity.ContentType;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.CloseableHttpClient;
import org.apache.http.message.BasicNameValuePair;
import org.apache.http.util.EntityUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.util.StringUtils;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.CountDownLatch;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Created by liang on 2017/6/6.
 */
@Component("leoService")
public class LeoServiceImpl implements ILeoService {
    private static Log logger = LogFactory.getLog(LeoServiceImpl.class);

    static int count = 0;
    @Override
    public LeoMessage refreshPrice(String cookie, String name) {
        return refreshPrice(cookie, name, false);
    }

    @Override
    public LeoMessage refreshPrice(String cookie, String name, boolean notRecive) {
        SimpleDateFormat s1 = new SimpleDateFormat("HH:mm:ss");
        String d1 = s1.format(new Date());
        long t1 = System.currentTimeMillis();
        logger.error((notRecive ? "(激活cookie)" : "") + "刷新价格-访问时间：" + d1);
        LeoMessage leoMessage = new LeoMessage();
        URL realUrl = null;
        HttpURLConnection conn = null;
        try {
            realUrl = new URL("http://www.platform.leocoin.org/Default.aspx");
            conn = (HttpURLConnection) realUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.setUseCaches(false);
            if (notRecive) {
                conn.setReadTimeout(30000);
                conn.setConnectTimeout(3000);
            } else {
                conn.setReadTimeout(500000);
                conn.setConnectTimeout(300000);
            }
            conn.setInstanceFollowRedirects(false);
            conn.setRequestProperty("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
            conn.setRequestProperty("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
            conn.setRequestProperty("Cache-Control", "max-age=0");
            conn.setRequestProperty("Connection", "keep-alive");
            conn.setRequestProperty("Cookie", cookie);
            conn.setRequestProperty("Host", "www.platform.leocoin.org");
            conn.setRequestProperty("Referer", "http://www.platform.leocoin.org/Authentication.aspx");
            conn.setRequestProperty("Upgrade-Insecure-Requests", "1");
            conn.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");

            int code = conn.getResponseCode();

            if (code == 200 || code == 302) {
                InputStream is = conn.getInputStream();
                BufferedReader in = new BufferedReader(new InputStreamReader(is, "UTF-8"));
                StringBuffer buffer = new StringBuffer();
                String line = "";
                while ((line = in.readLine()) != null) {
                    buffer.append(line);
                }
                String result = buffer.toString();
                int index = result.indexOf("ctl00$ContentPlaceHolder1$txtBuyMinPrice_value");
                long l2 = System.currentTimeMillis();
                String d2 = s1.format(new Date());
                if (index > 0) {
                    String pricePiece = result.substring(index, index + 80);
                    Pattern pattern = Pattern.compile("value=\"([\\d|.]*)\"");
                    Matcher matcher = pattern.matcher(pricePiece);
                    if (matcher.find()) {
                        pricePiece = matcher.group(1);
                    }
                    String msg = "【开始:" + d1 + "结束:" + d2 + ";响应耗时：" + (l2 - t1) / 1000 + "秒;价格：" + pricePiece + "】";
                    leoMessage.setPrice(pricePiece);
                    leoMessage.setLoginError(false);
                    leoMessage.setMsg("价格刷新成功！");
                }
                in.close();
                is.close();
            } else {
                leoMessage.setPrice("");
                leoMessage.setMsg("价格获取失败，请点击重新登录！");
                leoMessage.setLoginError(true);
            }
        } catch (Exception e) {
            logger.error("刷新价格出错", e);
            leoMessage.setPrice("");
            leoMessage.setMsg("刷新失败，Leo平台网络繁忙!");
            leoMessage.setLoginError(true);
        } finally {
            if (conn != null) {
                conn.disconnect();
            }
        }
        long t2 = System.currentTimeMillis();
        String d2 = s1.format(new Date());
        if (!notRecive) {
            logger.error((notRecive ? "(激活cookie)" : "") + "返回时间：" + d2 + "  耗时：" + (t2 - t1) + "ms");
        }
        leoMessage.setName(name);
        return leoMessage;
    }

    @Override
    public LeoMessage commitForm(String cookie, String price, String size) {

        long t1 = System.currentTimeMillis();
        logger.debug("提交订单：----第一步，点击[Sell Order]，cookie：" + cookie.substring(0, 20));

        String url = "http://www.platform.leocoin.org/SellCoin.aspx?TotalCoin=" + size + "&Price=" + price;
        String html = HttpClientUtil.sendGetRequestReturnWithHtml(cookie, url, null);
        logger.debug("提交订单：----第二步，[点击确认]，cookie：" + cookie.substring(0, 20));
        String param1 = "__VIEWSTATE";
        String param2 = "__EVENTVALIDATION";
        Pattern pattern = Pattern.compile("id=\"__VIEWSTATE\" value=\"([\\S]*)\"");
        Matcher matcher = pattern.matcher(html);
        String value1 = "";
        if (matcher.find()) {
            value1 = matcher.group(1);
        }
        pattern = Pattern.compile("id=\"__EVENTVALIDATION\" value=\"([\\S]*)\"");
        matcher = pattern.matcher(html);
        String value2 = "";
        if (matcher.find()) {
            value2 = matcher.group(1);
        }
        if (org.springframework.util.StringUtils.isEmpty(value1) || org.springframework.util.StringUtils.isEmpty(value2)) {
            logger.debug("提交订单：----第一步出错，点击确认页面，没有拿到有效的信息。，cookie：" + cookie.substring(0, 20));
        }
        String reqURL = url;
        String sendData = param1 + "=" + value1 + "&" + param2 + "=" + value2 + "&ctl00$ContentPlaceHolder1$btnSell=Confirm";
        String responseHtml = sendPostRequest(reqURL, sendData, cookie, true, null, null, null);
        LeoMessage leoMessage = new LeoMessage();
        long t2 = System.currentTimeMillis();
        if (responseHtml.indexOf("Your order has been saved") > -1) {
//            leoMessage.setMsg("订单提交成功! 耗时：" + (t2 - t1) / 1000 + "秒");
            leoMessage.setMsg("订单提交成功!");
            leoMessage.setLoginError(false);
        } else {
            leoMessage.setLoginError(true);
//            leoMessage.setMsg("订单提交失败！ 耗时：" + (t2 - t1) / 1000 + "秒");
            leoMessage.setMsg("订单提交失败！");
        }
        logger.debug(leoMessage.getMsg());
        return leoMessage;
    }

    @Override
    public LeoMessage getCookie(String userInfo) {
        String user = "";
        if (StringUtils.hasText(userInfo)) {
            user = userInfo;
        } else {
            return null;
        }
        user = user.trim().replaceAll("  ", " ");
        String[] userArr = user.split(" ");

        try {
            logger.error("step-1,访问网页，获取cookie");
            Map<String, String> map = getReponseString("https://www.learnearnown.com/");
            logger.error("step-2,登录网页，使cookie生效");

            String cookie = map.get("cookie");
            String reqURL = "https://www.learnearnown.com/";
            String sendData =
                    "ctl00$hdlid=1" +
                            "&ctl00$hdlname=English" +
                            "&ctl00$chkRememberMe=on" +
                            "&ctl00$btnLoginHeader=Login" +
                            "&ctl00$hdnContentType=0" +
                            "&ctl00$hdFlagURL=/assets/images/flags/24/United_Kingdom.png" +
                            "&ctl00$btnLoginHeader=Login" +
                            "&__SCROLLPOSITIONY=210" +
                            "&__SCROLLPOSITIONY=0"
                            + "&__VIEWSTATE=/wEPDwULLTE0MjU1NzkyMjQPZBYCZg9kFgICAw9kFg4CBg8PFgIeBFRleHQFCMKjIC0gR0JQZGQCBw8WAh4LXyFJdGVtQ291bnQCCRYSAgEPZBYCZg8VBAMxODMHJCAtIFVTRAExByQgLSBVU0RkAgIPZBYCZg8VBAIyOQckIC0gQ0FEATMHJCAtIENBRGQCAw9kFgJmDxUEAzE4MQjCoyAtIEdCUAE0CMKjIC0gR0JQZAIED2QWAmYPFQQACeKCrCAtIEVVUgE1CeKCrCAtIEVVUmQCBQ9kFgJmDxUEAzEzMQlScy4gLSBQS1IBNglScy4gLSBQS1JkAgYPZBYCZg8VBAMxNzYJ4oK6IC0gVFJZATcJ4oK6IC0gVFJZZAIHD2QWAmYPFQQDMTM2CuKCsSAtIFBlc28BOQrigrEgLSBQZXNvZAIID2QWAmYPFQQCNzkIUnAgLSBJRFICMTEIUnAgLSBJRFJkAgkPZBYCZg8VBAI3OAnigrkgLSBJTlICMTIJ4oK5IC0gSU5SZAIJDxYCHwECBxYOZg9kFgZmDxUBAzk2OWQCAQ8WAh8ABRBMRU8gU3RhcnRlciBQYWNrZAICDxUCAzk2ORBMRU8gU3RhcnRlciBQYWNrZAIBD2QWBmYPFQEDOTcwZAIBDxYCHwAFEUxFTyBCdXNpbmVzcyBQYWNrZAICDxUCAzk3MBFMRU8gQnVzaW5lc3MgUGFja2QCAg9kFgZmDxUBAzk3MWQCAQ8WAh8ABQxMRU8gVklQIFBhY2tkAgIPFQIDOTcxDExFTyBWSVAgUGFja2QCAw9kFgZmDxUBBDEwMDNkAgEPFgIfAAUUQ2hpbGQgRWR1Y2F0aW9uIFBhY2tkAgIPFQIEMTAwMxRDaGlsZCBFZHVjYXRpb24gUGFja2QCBA9kFgZmDxUBAzg2MWQCAQ8WAh8ABQlHb2xkIFBhY2tkAgIPFQIDODYxCUdvbGQgUGFja2QCBQ9kFgZmDxUBAzkwN2QCAQ8WAh8ABSRRdWljayBXaW5zIFNlcmllcyB0byBCdWlsZCBZb3VyIFRlYW1kAgIPFQIDOTA3JFF1aWNrIFdpbnMgU2VyaWVzIHRvIEJ1aWxkIFlvdXIgVGVhbWQCBg9kFgZmDxUBAzQyOGQCAQ8WAh8ABRxUaGUgUG93ZXIgb2YgU21hcnQgUXVlc3Rpb25zZAICDxUCAzQyOBxUaGUgUG93ZXIgb2YgU21hcnQgUXVlc3Rpb25zZAIKDw8WAh4HVmlzaWJsZWhkZAIMDw8WAh8CaGRkAiwPZBYKAgUPZBYCAgkPEGRkFgBkAgYPZBYGAgkPEGRkFgBkAgsPZBYCAgMPEGRkFgFmZAIVD2QWAgIDDxBkZBYBZmQCBw9kFgYCCQ8QZGQWAGQCDQ8QZGQWAGQCFw9kFgICAQ8QZGQWAWZkAggPZBYEAgkPEGRkFgBkAg0PEGRkFgBkAgkPZBYEAgkPEGRkFgBkAg0PEGRkFgBkAi0PZBYIAgMPFgIfAQIFFgoCAQ9kFgRmDxUCATEiL2Fzc2V0cy9pbWFnZXMvc2xpZGVycy9JbWFnZTkwLmpwZ2QCAQ8WAh8BAgIWBGYPZBYCZg8VAbEIPGRpdiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1fZGFyayBjdXN0b21pbiBjdXN0b21vdXQgdHAtcmVzaXplbWUgICBiYW5uZXJfcCINCmlkPSJzbGlkZTMtbGF5ZXIyIg0KZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiINCmRhdGEteT0iICIgZGF0YS12b2Zmc2V0PSIiDQpkYXRhLWVsZW1lbnRkZWxheT0iIg0KZGF0YS1zdGFydD0iMTIwMCINCmRhdGEtc3BlZWQ9IjYwMCINCmRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCINCmRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyINCmRhdGEtY3VzdG9tb3V0PSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MC43NTtzY2FsZVk6MC43NTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjYwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDUwJTsiDQpkYXRhLWNhcHRpb25oaWRkZW49Im9uIg0KZGF0YS13aWR0aD0iWyc0NDBweCcsJzQ0MHB4JywnNDAwcHgnLCcxNjBweCddIg0KZGF0YS1oZWlnaHQ9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddIg0KZGF0YS1zcGxpdGluPSJub25lIg0KZGF0YS1zcGxpdG91dD0ibm9uZSINCmRhdGEtcmVzcG9uc2l2ZV9vZmZzZXQ9Im9uIg0KZGF0YS1kZWxheT0iMjAwIg0Kc3R5bGU9Im1hcmdpbi10b3A6MzEwcHg7IG1hcmdpbi1ib3R0b206MjBweDsgZm9udC1zaXplOiAxNnB4OyBsZXR0ZXItc3BhY2luZzogbm9ybWFsOyBsaW5lLWhlaWdodDogMjBweDsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgY29sb3I6ICNGRkY7Ij4NCklmIHlvdSBhdHRlbmVkZWQgdGhlIExFTyBNb21lbnR1bSBUb3VycyBvZiAyMDE4LCB5b3Uga25vdyBqdXN0IGhvdyBwb3dlcmZ1bCB0aGVzZSBldmVudHMgY2FuIGJlISBZb3Ugb25seSBoYXZlIHVudGlsIDI4IEZlYnJ1YXJ5IDIwMTkgdG8gcXVhbGlmeSEgDQo8L2Rpdj5kAgEPZBYCZg8VAaEHPGEgaHJlZj0iaHR0cDovL21vbWVudHVtLmxlYXJuZWFybm93bi5jb20vDQoiIHRhcmdldD0iX2JsYW5rIiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1fZGFyayBiYW5uZXJfYnRuICBjdXN0b21pbiBjdXN0b21vdXQgdHAtcmVzaXplbWUgYnRuIGJ0bi1wcmltYXJ5Ig0KaWQ9InNsaWRlNi1sYXllcjIiDQpkYXRhLXg9IjAiIGRhdGEtaG9mZnNldD0iIg0KZGF0YS15PSIiIGRhdGEtdm9mZnNldD0iIg0KZGF0YS1lbGVtZW50ZGVsYXk9IiINCmRhdGEtc3RhcnQ9IjE0MDAiDQpkYXRhLXNwZWVkPSI2MDAiDQpkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiDQpkYXRhLWN1c3RvbWluPSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6OTA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjE7c2NhbGVZOjE7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZToyMDA7dHJhbnNmb3JtT3JpZ2luOjUwJSAwJTsiDQpkYXRhLWN1c3RvbW91dD0ieDowO3k6MDt6OjA7cm90YXRpb25YOjA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjAuNzU7c2NhbGVZOjAuNzU7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZTo2MDA7dHJhbnNmb3JtT3JpZ2luOjUwJSA1MCU7Ig0KZGF0YS1jYXB0aW9uaGlkZGVuPSJvbiINCmRhdGEtd2lkdGg9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddIg0KZGF0YS1oZWlnaHQ9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddIg0KZGF0YS1zcGxpdGluPSJub25lIg0KZGF0YS1zcGxpdG91dD0ibm9uZSINCmRhdGEtcmVzcG9uc2l2ZV9vZmZzZXQ9Im9uIg0KZGF0YS1kZWxheT0iMjAwIiBzdHlsZT0iYmFja2dyb3VuZDogI2ZmMjVmMjsgbWFyZ2luLWxlZnQ6IDUwcHg7IGRpc3BsYXk6aW5saW5lLWJsb2NrIj5tb3JlIGluZm8NCjwvYT5kAgIPZBYEZg8VAgEyKC9hc3NldHMvaW1hZ2VzL3NsaWRlcnMvc2xpZGVyaW1hZ2VkMy5qcGdkAgEPFgIfAQIFFgpmD2QWAmYPFQGNCjxkaXYgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtbGFyZ2VfbGlnaHRfd2hpdGVfY2VudGVyIGN1c3RvbWluIGN1c3RvbW91dCBzdGFydCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgaWQ9InNsaWRlMS1sYXllcjEiICAgICAgIGRhdGEteD0iY2VudGVyIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLWhvZmZzZXQ9IjAiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEteT0iMCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7IiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLWN1c3RvbW91dD0ieDowO3k6MDt6OjA7cm90YXRpb25YOjA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjAuNzU7c2NhbGVZOjAuNzU7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZTo2MDA7dHJhbnNmb3JtT3JpZ2luOjUwJSA1MCU7IiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLXNwZWVkPSIxMDAwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLXN0YXJ0PSI2MDAiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1lbmRzcGVlZD0iMzAwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBzdHlsZT0iZm9udC1zaXplOiAyNXB4OyBtYXJnaW4tdG9wOjE1MHB4OyBtYXJnaW4tYm90dG9tOjIwcHg7IHdoaXRlLXNwYWNlOm5vcm1hbCAhaW1wb3J0YW50Ij4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgVGhyb3VnaCBkZWxpdmVyaW5nIGtub3dsZWRnZSB3ZSBpbnNwaXJlIHBlb3BsZSB0byBsaXZlIHRoZWlyIGRyZWFtLiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PmQCAQ9kFgJmDxUBpQY8ZGl2IGNsYXNzPSJsZW9fYnRucyBjbGVhcmZpeCIgID4NCiAgPGRpdiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1sYXJnZV9saWdodF93aGl0ZV9jZW50ZXIgY3VzdG9taW4gY3VzdG9tb3V0IHN0YXJ0IGxheWVyMiB0cC1yZXNpemVtZSBsZWFybl9kaXYiIGlkPSJzbGlkZTEtbGF5ZXIyIiBkYXRhLXg9IjAiICBkYXRhLWhvZmZzZXQ9IiIgZGF0YS15PSIiIGRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyIgZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyIgZGF0YS1zcGVlZD0iMTAwMCIgZGF0YS1zdGFydD0iODAwIiBkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiIGRhdGEtZW5kc3BlZWQ9IjMwMCIgc3R5bGU9ImZvbnQtd2VpZ2h0OiA3MDA7IGZvbnQtc2l6ZTogNTBweDsgbGV0dGVyLXNwYWNpbmc6IDFweDsgbGluZS1oZWlnaHQ6IDUwcHg7IGNvbG9yOiB3aGl0ZTsgICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsiPjxhIGhyZWY9Ii9BYm91dExFTy9MZWFybiIgdGFyZ2V0PSJfYmxhbmsiIGNsYXNzPSJib3hlcyI+TEVBUk48L2E+PC9kaXY+ZAICD2QWAmYPFQGEBjxkaXYgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtbGFyZ2VfbGlnaHRfd2hpdGVfY2VudGVyIGN1c3RvbWluIGN1c3RvbW91dCBzdGFydCAgbGF5ZXIyIHRwLXJlc2l6ZW1lIGVhcm5fZGl2IiBpZD0ic2xpZGUxLWxheWVyMyIgZGF0YS14PSJjZW50ZXIiICBkYXRhLWhvZmZzZXQ9IiIgZGF0YS15PSIiIGRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyIgZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyIgZGF0YS1zcGVlZD0iMTAwMCIgZGF0YS1zdGFydD0iMTAwMCIgZGF0YS1lYXNpbmc9IkJhY2suZWFzZUluT3V0IiBkYXRhLWVuZHNwZWVkPSIzMDAiIHN0eWxlPSJmb250LXdlaWdodDogNzAwOyBmb250LXNpemU6IDUwcHg7IGxldHRlci1zcGFjaW5nOiAxcHg7IGxpbmUtaGVpZ2h0OiA1MHB4OyBjb2xvcjogd2hpdGU7ICAgICBkaXNwbGF5OiBpbmxpbmUtYmxvY2s7Ij48YSBocmVmPSIvQWJvdXRMRU8vRWFybiIgdGFyZ2V0PSJfYmxhbmsiIGNsYXNzPSJib3hlcyI+RUFSTjwvYT48L2Rpdj5kAgMPZBYCZg8VAa8GPGRpdiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1sYXJnZV9saWdodF93aGl0ZV9jZW50ZXIgY3VzdG9taW4gY3VzdG9tb3V0IHN0YXJ0IGxheWVyMiB0cC1yZXNpemVtZSBvd25fZGl2IiBpZD0ic2xpZGUxLWxheWVyNCIgIGRhdGEteD0iY2VudGVyIiBkYXRhLWhvZmZzZXQ9IiIgZGF0YS15PSIiIGRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyIgZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyIgZGF0YS1zcGVlZD0iMTAwMCIgZGF0YS1zdGFydD0iMTIwMCIgZGF0YS1lYXNpbmc9IkJhY2suZWFzZUluT3V0IiBkYXRhLWVuZHNwZWVkPSIzMDAiIHN0eWxlPSJmb250LXdlaWdodDogNzAwOyBmb250LXNpemU6IDUwcHg7IGxldHRlci1zcGFjaW5nOiAxcHg7IGxpbmUtaGVpZ2h0OiA1MHB4OyBjb2xvcjogd2hpdGU7ICAgIGRpc3BsYXk6IGlubGluZS1ibG9jazsiPjxhIGhyZWY9Ii9BYm91dExFTy9Pd24iIHRhcmdldD0iX2JsYW5rIiBjbGFzcz0iYm94ZXMiPk9XTjwvYT48L2Rpdj4NCiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5kAgQPZBYCZg8VAZQMPGRpdiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1fZGFyayBjdXN0b21pbiBjdXN0b21vdXQgdHAtcmVzaXplbWUgY2xlYXJmaXggIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBpZD0ic2xpZGUxLWxheWVyNSIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS14PSJjZW50ZXIiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEteT0iIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLXNwbGl0aW49IiIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1lbGVtZW50ZGVsYXk9IiIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1zdGFydD0iMTQwMCIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1zcGVlZD0iNjAwIiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1jYXB0aW9uaGlkZGVuPSJvbiIgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS1ob2Zmc2V0PSIwIiBkYXRhLXdpZHRoPSdbIjcwMHB4IiwiNjAwcHgiLCI0MDBweCIsIjMwMHB4Il0nIHN0eWxlPSJjb2xvcjogd2hpdGU7IGZvbnQtc2l6ZTogMjVweDsgbGluZS1oZWlnaHQ6IDYwcHg7IGZvbnQtd2VpZ2h0OiAzMDA7IGxldHRlci1zcGFjaW5nOiAwcHg7IHRleHQtYWxpZ246Y2VudGVyOyB3aGl0ZS1zcGFjZTogbm9ybWFsOyBtYXJnaW4tdG9wOjIwcHg7IGxpbmUtaGVpZ2h0OiAyNXB4Ij4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgV2Ugb2ZmZXIgYW4gaW5ub3ZhdGl2ZSBhbmQgY3JlYXRpdmUgYXBwcm9hY2ggdG8gbGVhcm5pbmcgd2l0aCBtdWx0aWxpbmd1YWwgcHJvZHVjdHMgZm9yIGZsZXhpYmxlLCBoYW5kcy1vbiBsZWFybmluZy4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5kAgMPZBYEZg8VAgEzIi9hc3NldHMvaW1hZ2VzL3NsaWRlcnMvSW1hZ2U3Ni5qcGdkAgEPFgIfAQIDFgZmD2QWAmYPFQHVCDxkaXYgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtX2RhcmsgY3VzdG9taW4gY3VzdG9tb3V0IHRwLXJlc2l6ZW1lICAgYmFubmVyX2gxIg0KICAgICBpZD0ic2xpZGUzLWxheWVyMSINCiAgICAgZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiINCiAgICAgZGF0YS15PSIiIGRhdGEtdm9mZnNldD0iIg0KICAgICBkYXRhLWVsZW1lbnRkZWxheT0iIg0KICAgICBkYXRhLXN0YXJ0PSIxMDAwIg0KICAgICBkYXRhLXNwZWVkPSI2MDAiDQogICAgIGRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCINCiAgICAgZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7Ig0KICAgICBkYXRhLWN1c3RvbW91dD0ieDowO3k6MDt6OjA7cm90YXRpb25YOjA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjAuNzU7c2NhbGVZOjAuNzU7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZTo2MDA7dHJhbnNmb3JtT3JpZ2luOjUwJSA1MCU7Ig0KICAgICBkYXRhLWNhcHRpb25oaWRkZW49Im9uIg0KICAgICBkYXRhLXdpZHRoPSJbJzYwMHB4JywnNjAwcHgnLCczNTBweCcsJzIwMHB4J10iDQogICAgIGRhdGEtaGVpZ2h0PSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSINCiAgICAgZGF0YS1zcGxpdGluPSJub25lIg0KICAgICBkYXRhLXNwbGl0b3V0PSJub25lIg0KICAgICBkYXRhLXJlc3BvbnNpdmVfb2Zmc2V0PSJvbiINCiAgICAgZGF0YS1kZWxheT0iMjAwIg0KICAgICBzdHlsZT0ibWFyZ2luLXRvcDoxNTBweDsgbWFyZ2luLWJvdHRvbToxM3B4OyB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOyBjb2xvcjogI0ZGRjsgd29yZC13cmFwOiBub3JtYWw7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGxldHRlci1zcGFjaW5nOiAwLjZweDsgZm9udC13ZWlnaHQ6IGJvbGQ7IGxpbmUtaGVpZ2h0OiA1MHB4OyI+DQogICAgSW50cm9kdWNpbmcgdGhlIG5ldyBsZWFkaW5nIHBsYXllcnMgZnJvbSBMRU8NCg0KPC9kaXY+ZAIBD2QWAmYPFQHYCDxkaXYgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtX2RhcmsgY3VzdG9taW4gY3VzdG9tb3V0IHRwLXJlc2l6ZW1lICAgYmFubmVyX3AiDQppZD0ic2xpZGUzLWxheWVyMiINCmRhdGEteD0iMCIgZGF0YS1ob2Zmc2V0PSIiDQpkYXRhLXk9IiAiIGRhdGEtdm9mZnNldD0iIg0KZGF0YS1lbGVtZW50ZGVsYXk9IiINCmRhdGEtc3RhcnQ9IjEyMDAiDQpkYXRhLXNwZWVkPSI2MDAiDQpkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiDQpkYXRhLWN1c3RvbWluPSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6OTA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjE7c2NhbGVZOjE7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZToyMDA7dHJhbnNmb3JtT3JpZ2luOjUwJSAwJTsiDQpkYXRhLWN1c3RvbW91dD0ieDowO3k6MDt6OjA7cm90YXRpb25YOjA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjAuNzU7c2NhbGVZOjAuNzU7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZTo2MDA7dHJhbnNmb3JtT3JpZ2luOjUwJSA1MCU7Ig0KZGF0YS1jYXB0aW9uaGlkZGVuPSJvbiINCmRhdGEtd2lkdGg9IlsnNTUwcHgnLCc0MDBweCcsJzMwMHB4JywnMTMwcHgnXSINCmRhdGEtaGVpZ2h0PSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSINCmRhdGEtc3BsaXRpbj0ibm9uZSINCmRhdGEtc3BsaXRvdXQ9Im5vbmUiDQpkYXRhLXJlc3BvbnNpdmVfb2Zmc2V0PSJvbiINCmRhdGEtZGVsYXk9IjIwMCINCnN0eWxlPSJtYXJnaW4tYm90dG9tOjIwcHg7IGZvbnQtc2l6ZTogMTZweDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDIwcHg7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGNvbG9yOiAjRkZGOyI+DQpMRU8gaXMgcHJvdWQgdG8gYW5ub3VuY2UgdGhlIGxhdW5jaCBvZiAzIG5ldyBQcm9kdWN0IFBhY2tzLCB3aGljaCBpcyBncmVhdCBuZXdzIGZvciB5b3UgYW5kIHlvdXIgdGVhbSwgeW91ciBwcm9zcGVjdHMgYW5kLCBiZWNhdXNlIGl0IHdpbGwgc3BlZWQgeW91IHRvd2FyZHMgeW91ciBMZWFybiwgRWFybiBhbmQgT3duIGdvYWxzLCBmb3IgTEVPIHRvby4NCjwvZGl2Pg0KZAICD2QWAmYPFQHLBzxhIGhyZWY9Imh0dHBzOi8vd3d3LmxlYXJuZWFybm93bi5jb20vbGVvL1Nob3AvQ2F0ZWdvcnkvUHJvZHVjdC1QYWNrcyIgdGFyZ2V0PSJfYmxhbmsiIGNsYXNzPSJ0cC1jYXB0aW9uIG1lZGl1bV9kYXJrIGN1c3RvbWluIGN1c3RvbW91dCB0cC1yZXNpemVtZSBidG4gYnRuLXByaW1hcnkgYmFubmVyX2J0biIgIHN0eWxlPSJiYWNrZ3JvdW5kLWNvbG9yOiNkNTNiNTggIWltcG9ydGFudDsgZGlzcGxheTppbmxpbmUtYmxvY2siICBpZD0ic2xpZGUzLWxheWVyMyIgICBkYXRhLXg9IjAiIGRhdGEtaG9mZnNldD0iIiAgIGRhdGEteT0iIiBkYXRhLXZvZmZzZXQ9IiIgICBkYXRhLWVsZW1lbnRkZWxheT0iIiAgIGRhdGEtc3RhcnQ9IjE0MDAiICAgZGF0YS1zcGVlZD0iNjAwIiAgIGRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCIgICBkYXRhLWN1c3RvbWluPSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6OTA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjE7c2NhbGVZOjE7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZToyMDA7dHJhbnNmb3JtT3JpZ2luOjUwJSAwJTsiICAgZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyIgICBkYXRhLWNhcHRpb25oaWRkZW49Im9uIiAgIGRhdGEtd2lkdGg9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddIiAgIGRhdGEtaGVpZ2h0PSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSIgICBkYXRhLXNwbGl0aW49Im5vbmUiICAgZGF0YS1zcGxpdG91dD0ibm9uZSIgICBkYXRhLXJlc3BvbnNpdmVfb2Zmc2V0PSJvbiIgICBkYXRhLWRlbGF5PSIyMDAiPiAgIEZJTkQgT1VUIE1PUkU8L2E+ZAIED2QWBGYPFQIBNCIvYXNzZXRzL2ltYWdlcy9zbGlkZXJzL0ltYWdlNjguanBnZAIBDxYCHwECAxYGZg9kFgJmDxUB5wg8ZGl2IGNsYXNzPSJ0cC1jYXB0aW9uIG1lZGl1bV9kYXJrIGN1c3RvbWluIGN1c3RvbW91dCB0cC1yZXNpemVtZSBiYW5uZXJfaDEgIg0KICAgICBpZD0ic2xpZGUzLWxheWVyMSINCiAgICAgZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiINCiAgICAgZGF0YS15PSIiIGRhdGEtdm9mZnNldD0iIg0KICAgICBkYXRhLWVsZW1lbnRkZWxheT0iIg0KICAgICBkYXRhLXN0YXJ0PSIxMDAwIg0KICAgICBkYXRhLXNwZWVkPSI2MDAiDQogICAgIGRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCINCiAgICAgZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7Ig0KICAgICBkYXRhLWN1c3RvbW91dD0ieDowO3k6MDt6OjA7cm90YXRpb25YOjA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjAuNzU7c2NhbGVZOjAuNzU7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZTo2MDA7dHJhbnNmb3JtT3JpZ2luOjUwJSA1MCU7Ig0KICAgICBkYXRhLWNhcHRpb25oaWRkZW49Im9uIg0KICAgICBkYXRhLXdpZHRoPSJbJzYwMHB4JywnNjAwcHgnLCczNTBweCcsJzIwMHB4J10iDQogICAgIGRhdGEtaGVpZ2h0PSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSINCiAgICAgZGF0YS1zcGxpdGluPSJub25lIg0KICAgICBkYXRhLXNwbGl0b3V0PSJub25lIg0KICAgICBkYXRhLXJlc3BvbnNpdmVfb2Zmc2V0PSJvbiINCiAgICAgZGF0YS1kZWxheT0iMjAwIg0KICAgICBzdHlsZT0ibWFyZ2luLXRvcDoxNTBweDsgbWFyZ2luLWJvdHRvbToyMHB4OyB0ZXh0LXRyYW5zZm9ybTogdXBwZXJjYXNlOyBjb2xvcjogI0ZGRjsgd29yZC13cmFwOiBub3JtYWw7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGxldHRlci1zcGFjaW5nOiAwLjZweDsgZm9udC13ZWlnaHQ6IGJvbGQ7IGxpbmUtaGVpZ2h0OiA1MHB4OyI+DQogICAgT3VyIG1pc3Npb24gaXMgc2VydmljZSB0byBtYW5raW5kIGJ5IHVubGVhc2hpbmcgaHVtYW4gcG90ZW50aWFsDQoNCjwvZGl2PmQCAQ9kFgJmDxUB5gg8ZGl2IGNsYXNzPSJ0cC1jYXB0aW9uIG1lZGl1bV9kYXJrIGN1c3RvbWluIGN1c3RvbW91dCB0cC1yZXNpemVtZSBiYW5uZXJfcCINCmlkPSJzbGlkZTMtbGF5ZXIyIg0KZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiINCmRhdGEteT0iIiBkYXRhLXZvZmZzZXQ9IiINCmRhdGEtZWxlbWVudGRlbGF5PSIiDQpkYXRhLXN0YXJ0PSIxMjAwIg0KZGF0YS1zcGVlZD0iNjAwIg0KZGF0YS1lYXNpbmc9IkJhY2suZWFzZUluT3V0Ig0KZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7Ig0KZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyINCmRhdGEtY2FwdGlvbmhpZGRlbj0ib24iDQpkYXRhLXdpZHRoPSJbJzYwMHB4JywnNjAwcHgnLCczNTBweCcsJzIwMHB4J10iDQpkYXRhLWhlaWdodD0iWydhdXRvJywnYXV0bycsJ2F1dG8nLCdhdXRvJ10iDQpkYXRhLXNwbGl0aW49Im5vbmUiDQpkYXRhLXNwbGl0b3V0PSJub25lIg0KZGF0YS1yZXNwb25zaXZlX29mZnNldD0ib24iDQpkYXRhLWRlbGF5PSIyMDAiDQpzdHlsZT0ibWFyZ2luLWJvdHRvbToyMHB4O2ZvbnQtc2l6ZTogMTZweDsgbGV0dGVyLXNwYWNpbmc6IG5vcm1hbDsgbGluZS1oZWlnaHQ6IDIwcHg7IHdoaXRlLXNwYWNlOiBub3JtYWw7IGNvbG9yOiAjRkZGOyI+DQpUaHJvdWdoIGRlbGl2ZXJpbmcga25vd2xlZGdlIGFuZCB0aGUgbWVhbnMgdG8gZmFjaWxpdGF0ZSBlbnRyZXByZW5ldXJzaGlwLCB3ZSBpbnNwaXJlIHBlb3BsZSB0byBsaXZlIHRoZWlyIGRyZWFtLiBBcyBhIGdsb2JhbCBvcmdhbml6YXRpb24sIHdlIHZhbHVlIGN1bHR1cmFsIGRpdmVyc2l0eSBhbmQgaGF2ZSBidWlsdCBhIGNvbXBhbnkgdGhhdCBpcyBpbmNsdXNpdmUgZm9yIGFsbC4NCg0KPC9kaXY+ZAICD2QWAmYPFQGlBzxhIGhyZWY9Imh0dHBzOi8vd3d3LmxlYXJuZWFybm93bi5jb20vbGVvL0Fib3V0TEVPL1Zpc2lvbk1pc3Npb24iIHRhcmdldD0iX2JsYW5rIiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1fZGFyayBjdXN0b21pbiBjdXN0b21vdXQgdHAtcmVzaXplbWUgYnRuIGJ0bi1wcmltYXJ5ICBiYW5uZXJfYnRuIiAgIGlkPSJzbGlkZTMtbGF5ZXIzIiAgc3R5bGU9IiBkaXNwbGF5OmlubGluZS1ibG9jayIgICAgZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiIgICBkYXRhLXk9IiIgZGF0YS12b2Zmc2V0PSIiICAgZGF0YS1lbGVtZW50ZGVsYXk9IiIgICBkYXRhLXN0YXJ0PSIxNDAwIiAgIGRhdGEtc3BlZWQ9IjYwMCIgICBkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiICAgZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7IiAgIGRhdGEtY3VzdG9tb3V0PSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MC43NTtzY2FsZVk6MC43NTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjYwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDUwJTsiICAgZGF0YS1jYXB0aW9uaGlkZGVuPSJvbiIgICBkYXRhLXdpZHRoPSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSIgICBkYXRhLWhlaWdodD0iWydhdXRvJywnYXV0bycsJ2F1dG8nLCdhdXRvJ10iICAgZGF0YS1zcGxpdGluPSJub25lIiAgIGRhdGEtc3BsaXRvdXQ9Im5vbmUiICAgZGF0YS1yZXNwb25zaXZlX29mZnNldD0ib24iICAgZGF0YS1kZWxheT0iMjAwIj4gICBGSU5EIE9VVCBNT1JFPC9hPmQCBQ9kFgRmDxUCATUiL2Fzc2V0cy9pbWFnZXMvc2xpZGVycy9JbWFnZTc4LmpwZ2QCAQ8WAh8BAgMWBmYPZBYCZg8VAfwHPGRpdiBjbGFzcz0idHAtY2FwdGlvbiBtZWRpdW1fZGFyayBjdXN0b21pbiBjdXN0b21vdXQgdHAtcmVzaXplbWUgIGJhbm5lcl9oMSAiDQppZD0ic2xpZGU1LWxheWVyMSINCmRhdGEteD0iMCIgZGF0YS1ob2Zmc2V0PSIiDQpkYXRhLXk9IiIgZGF0YS12b2Zmc2V0PSIiDQpkYXRhLWVsZW1lbnRkZWxheT0iIg0KZGF0YS1zdGFydD0iMTAwMCINCmRhdGEtc3BlZWQ9IjYwMCINCmRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCINCmRhdGEtY3VzdG9taW49Ing6MDt5OjA7ejowO3JvdGF0aW9uWDo5MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MTtzY2FsZVk6MTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjIwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDAlOyINCmRhdGEtY3VzdG9tb3V0PSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MC43NTtzY2FsZVk6MC43NTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjYwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDUwJTsiDQpkYXRhLWNhcHRpb25oaWRkZW49Im9uIg0KZGF0YS13aWR0aD0iWyc2MDBweCcsJzYwMHB4JywnMzUwcHgnLCcyMDBweCddIg0KZGF0YS1oZWlnaHQ9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddIg0KZGF0YS1zcGxpdGluPSJub25lIg0KZGF0YS1zcGxpdG91dD0ibm9uZSINCmRhdGEtcmVzcG9uc2l2ZV9vZmZzZXQ9Im9uIg0KZGF0YS1kZWxheT0iMjAwIg0Kc3R5bGU9Im1hcmdpbi10b3A6MTUwcHg7ICBtYXJnaW4tYm90dG9tOjIwcHg7IHRleHQtdHJhbnNmb3JtOiB1cHBlcmNhc2U7IGNvbG9yOiAjRkZGOyB3b3JkLXdyYXA6IG5vcm1hbDsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgbGV0dGVyLXNwYWNpbmc6IDAuNnB4OyBmb250LXdlaWdodDogYm9sZDsgbGluZS1oZWlnaHQ6IDUwcHg7Ij4NCndlIGJlbGlldmUgdGhlcmUgaXMgZ3JlYXRuZXNzIGluc2lkZSBldmVyeW9uZQ0KPC9kaXY+ZAIBD2QWAmYPFQGZCTxkaXYgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtX2RhcmsgY3VzdG9taW4gY3VzdG9tb3V0IHRwLXJlc2l6ZW1lICBiYW5uZXJfcCIgaWQ9InNsaWRlNS1sYXllcjIiZGF0YS14PSIwIiBkYXRhLWhvZmZzZXQ9IiJkYXRhLXk9IiIgZGF0YS12b2Zmc2V0PSIiZGF0YS1lbGVtZW50ZGVsYXk9IiJkYXRhLXN0YXJ0PSIxMjAwImRhdGEtc3BlZWQ9IjYwMCJkYXRhLWVhc2luZz0iQmFjay5lYXNlSW5PdXQiZGF0YS1jdXN0b21pbj0ieDowO3k6MDt6OjA7cm90YXRpb25YOjkwO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDoxO3NjYWxlWToxO3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6MjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgMCU7ImRhdGEtY3VzdG9tb3V0PSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6MDtyb3RhdGlvblk6MDtyb3RhdGlvblo6MDtzY2FsZVg6MC43NTtzY2FsZVk6MC43NTtza2V3WDowO3NrZXdZOjA7b3BhY2l0eTowO3RyYW5zZm9ybVBlcnNwZWN0aXZlOjYwMDt0cmFuc2Zvcm1PcmlnaW46NTAlIDUwJTsiZGF0YS1jYXB0aW9uaGlkZGVuPSJvbiJkYXRhLXdpZHRoPSJbJzYwMHB4JywnNjAwcHgnLDM1MHB4JywnMjAwcHgnXSJkYXRhLWhlaWdodD0iWydhdXRvJywnYXV0bycsJ2F1dG8nLCdhdXRvJ10iZGF0YS1zcGxpdGluPSJub25lImRhdGEtc3BsaXRvdXQ9Im5vbmUiZGF0YS1yZXNwb25zaXZlX29mZnNldD0ib24iZGF0YS1kZWxheT0iMjAwIiBzdHlsZT0ibWFyZ2luLWJvdHRvbToyMHB4OyBsZXR0ZXItc3BhY2luZzogbm9ybWFsOyBsaW5lLWhlaWdodDogMjBweDsgd2hpdGUtc3BhY2U6IG5vcm1hbDsgY29sb3I6ICNGRkY7Ij5XZSBiZWxpZXZlIHRoYXQgaW4gZWFjaCBvbmUgb2YgeW91LCB0aGVyZSBpcyBncmVhdG5lc3Mgd2FpdGluZyB0byBtYW5pZmVzdC4gSXTigJlzIHBvc3NpYmxlIHRvIGJ1aWxkIGEgbG9uZyB0ZXJtIGJ1c2luZXNzIGJhc2VkIG9uIGRlc2lyZSBhbmQgcXVlc3QgdG8gZmluZCB0aGUgIndpbi13aW4iIGluIGV2ZXJ5IHNjZW5hcmlvLiBXZSByZWNvZ25pemUgdGhlIHdvcmxkIGlzIG1vdmluZyBmYXN0ZXIgYW5kIHRvIGFjaGlldmUgc3VjY2VzcyBpbiB0b2RheeKAmXMgd29ybGQsIHdlIGhhdmUgdG8gYmUgbW9yZSBhZ2lsZSBhbmQgYmUgcXVpY2tlciBvbiBvdXIgZmVldC48L2Rpdj5kAgIPZBYCZg8VAfMGPGEgaHJlZj0iaHR0cHM6Ly93d3cubGVhcm5lYXJub3duLmNvbS9sZW8vQWJvdXRMRU8vQ29tcGFueU92ZXJ2aWV3IiB0YXJnZXQ9Il9ibGFuayIgY2xhc3M9InRwLWNhcHRpb24gbWVkaXVtX2RhcmsgY3VzdG9taW4gY3VzdG9tb3V0IHRwLXJlc2l6ZW1lIGJ0biBidG4tcHJpbWFyeSBiYW5uZXJfYnRuIiBpZD0ic2xpZGU1LWxheWVyMyJkYXRhLXg9IjAiIGRhdGEtaG9mZnNldD0iImRhdGEteT0iIiBkYXRhLXZvZmZzZXQ9IiJkYXRhLWVsZW1lbnRkZWxheT0iImRhdGEtc3RhcnQ9IjE0MDAiZGF0YS1zcGVlZD0iNjAwImRhdGEtZWFzaW5nPSJCYWNrLmVhc2VJbk91dCJkYXRhLWN1c3RvbWluPSJ4OjA7eTowO3o6MDtyb3RhdGlvblg6OTA7cm90YXRpb25ZOjA7cm90YXRpb25aOjA7c2NhbGVYOjE7c2NhbGVZOjE7c2tld1g6MDtza2V3WTowO29wYWNpdHk6MDt0cmFuc2Zvcm1QZXJzcGVjdGl2ZToyMDA7dHJhbnNmb3JtT3JpZ2luOjUwJSAwJTsiZGF0YS1jdXN0b21vdXQ9Ing6MDt5OjA7ejowO3JvdGF0aW9uWDowO3JvdGF0aW9uWTowO3JvdGF0aW9uWjowO3NjYWxlWDowLjc1O3NjYWxlWTowLjc1O3NrZXdYOjA7c2tld1k6MDtvcGFjaXR5OjA7dHJhbnNmb3JtUGVyc3BlY3RpdmU6NjAwO3RyYW5zZm9ybU9yaWdpbjo1MCUgNTAlOyJkYXRhLWNhcHRpb25oaWRkZW49Im9uImRhdGEtd2lkdGg9IlsnYXV0bycsJ2F1dG8nLCdhdXRvJywnYXV0byddImRhdGEtaGVpZ2h0PSJbJ2F1dG8nLCdhdXRvJywnYXV0bycsJ2F1dG8nXSJkYXRhLXNwbGl0aW49Im5vbmUiZGF0YS1zcGxpdG91dD0ibm9uZSJkYXRhLXJlc3BvbnNpdmVfb2Zmc2V0PSJvbiJkYXRhLWRlbGF5PSIyMDAiICAgc3R5bGU9ImRpc3BsYXk6aW5saW5lLWJsb2NrIj5GSU5EIE9VVCBNT1JFPC9hPmQCCw8WAh8BAgYWDGYPZBYKZg8PFgIeCEltYWdlVXJsBUxodHRwczovL3d3dy5sZWFybmVhcm5vd24uY29tL2Fzc2V0cy9JbWFnZXMvUHJvZHVjdEltYWdlcy8xMDAzX21lZGl1bS5qcGc/dj0yZGQCAQ8WAh8ABRRDaGlsZCBFZHVjYXRpb24gUGFja2QCAg8WAh8ABY0CVGhlIENoaWxkIEVkdWNhdGlvbiBQYWNrIGludHJvZHVjZXMgYSBuZXcgYW5kIGV4Y2x1c2l2ZSBjYXRlZ29yeSB0byB0aGUgTEVPIGUtbGVhcm5pbmcgcGxhdGZvcm0gZm9jdXNzaW5nIG9uIFNvY2lhbCBFbnRyZXByZW5ldXJzaGlwLiBUaGlzIHBhY2sgYWxzbyBnaXZlcyB5b3UgdGhlIG9wcG9ydHVuaXR5IHRvIGVuZ2FnZSB3aXRoIHByb2plY3RzIGFpbWVkIGF0IGltcHJvdmluZyB0aGUgZWR1Y2F0aW9uIGZvciBjaGlsZHJlbiBpbiBkZXZlbG9waW5nIGNvdW50cmllcy5kAgMPFQIEMTAwMxRDaGlsZC1FZHVjYXRpb24tUGFja2QCBQ8WAh8ABQYxNTAuMDBkAgEPZBYKZg8PFgIfAwVLaHR0cHM6Ly93d3cubGVhcm5lYXJub3duLmNvbS9hc3NldHMvSW1hZ2VzL1Byb2R1Y3RJbWFnZXMvOTY5X21lZGl1bS5qcGc/dj0yZGQCAQ8WAh8ABRBMRU8gU3RhcnRlciBQYWNrZAICDxYCHwAFkgJUaGUgTEVPIFN0YXJ0ZXIgUGFjayBhbGxvd3MgeW91IHRvIGNob29zZSBmcm9tIG92ZXIgMTUwIExFTyBlbnRyZXByZW5ldXJzaGlwIHRyYWluaW5nIHByb2R1Y3RzIHdpdGggdW5saW1pdGVkIGFjY2VzcyBmb3IgMSBtb250aC4gWW91IGFsc28gcmVjZWl2ZSAxIExpdmUgU2VtaW5hciB0aWNrZXQgd2hpY2ggcHJvdmlkZXMgeW91IHdpdGggdGhlIG9wcG9ydHVuaXR5IHRvIGF0dGVuZCBhIGR5bmFtaWMgTGl2ZSBTZW1pbmFyIHRyYWluaW5nIHdpdGggdG9wLXRpZXIgdHJhaW5lcnMuZAIDDxUCAzk2ORBMRU8tU3RhcnRlci1QYWNrZAIFDxYCHwAFBjE1MC4wMGQCAg9kFgpmDw8WAh8DBUtodHRwczovL3d3dy5sZWFybmVhcm5vd24uY29tL2Fzc2V0cy9JbWFnZXMvUHJvZHVjdEltYWdlcy85NzBfbWVkaXVtLmpwZz92PTJkZAIBDxYCHwAFEUxFTyBCdXNpbmVzcyBQYWNrZAICDxYCHwAFlgJUaGUgTEVPIEJ1c2luZXNzIFBhY2sgYWxsb3dzIHlvdSB0byBjaG9vc2UgZnJvbSBodW5kcmVkcyBvZiBMRU8gZW50cmVwcmVuZXVyc2hpcCB0cmFpbmluZyBwcm9kdWN0cyB3aXRoIHVubGltaXRlZCBhY2Nlc3MgZm9yIDQgbW9udGhzLiBZb3UgYWxzbyByZWNlaXZlIDQgTGl2ZSBTZW1pbmFyIHRpY2tldHMgd2hpY2ggcHJvdmlkZSB5b3Ugd2l0aCB0aGUgb3Bwb3J0dW5pdHkgdG8gYXR0ZW5kIGR5bmFtaWMgTGl2ZSBTZW1pbmFyIHRyYWluaW5ncyB3aXRoIHRvcC10aWVyIHRyYWluZXJzLmQCAw8VAgM5NzARTEVPLUJ1c2luZXNzLVBhY2tkAgUPFgIfAAUGNjAwLjAwZAIDD2QWCmYPDxYCHwMFS2h0dHBzOi8vd3d3LmxlYXJuZWFybm93bi5jb20vYXNzZXRzL0ltYWdlcy9Qcm9kdWN0SW1hZ2VzLzk3MV9tZWRpdW0uanBnP3Y9MmRkAgEPFgIfAAUMTEVPIFZJUCBQYWNrZAICDxYCHwAF8gNUaGUgTEVPIFZJUCBQYWNrIGFsbG93cyB5b3UgdG8gY2hvb3NlIGZyb20gaHVuZHJlZHMgb2YgTEVPIGVudHJlcHJlbmV1cnNoaXAgdHJhaW5pbmcgcHJvZHVjdHMgd2l0aCB1bmxpbWl0ZWQgYWNjZXNzIGZvciAxMiBtb250aHMuIFlvdSBhbHNvIHJlY2VpdmUgNCBWSVAgTGl2ZSBTZW1pbmFyIHRpY2tldHMgd2hpY2ggcHJvdmlkZSB5b3Ugd2l0aCB0aGUgb3Bwb3J0dW5pdHkgdG8gYXR0ZW5kIGR5bmFtaWMgTEVPIExpdmUgU2VtaW5hciB0cmFpbmluZ3Mgd2l0aCB0b3AtdGllciB0cmFpbmVycy4gIFZJUCBMaXZlIFNlbWluYXIgVGlja2V0cyBpbmNsdWRlIHByaW9yaXR5IHNlYXRpbmcgYXQgdGhlIGV2ZW50IGFuZCBib251cyB0cmFpbmluZyBzZXNzaW9ucyAgYXMgd2VsbCBhcyBsdW5jaCBvciBkaW5uZXIgd2l0aCB0aGUgU2VtaW5hciB0cmFpbmVycy4gPGJyIC8+IDxiciAvPiA8Yj5Ob3RlOiBUaGlzIHByb2R1Y3QgaXMgbm90IGF2YWlsYWJsZSBpbiBQYWtpc3RhbjwvYj5kAgMPFQIDOTcxDExFTy1WSVAtUGFja2QCBQ8WAh8ABQgxLDUwMC4wMGQCBA9kFgpmDw8WAh8DBUtodHRwczovL3d3dy5sZWFybmVhcm5vd24uY29tL2Fzc2V0cy9JbWFnZXMvUHJvZHVjdEltYWdlcy83NDZfbWVkaXVtLmpwZz92PTJkZAIBDxYCHwAFJVRoZSBQb3dlciBvZiBTbWFydCBDdXN0b21lciBSZWxhdGlvbnNkAgIPFgIfAAXxBTxwPkNvbW11bmljYXRpb24gaXMga2V5LiBXaGV0aGVyIHlvdSBhcmUgc3BlYWtpbmcgd2l0aCB5b3VyIHRlYW0sIHdpdGggcHJvc3BlY3RpdmUgY2xpZW50cyBvciB3aXRoIGZhbWlseSBhbmQgZnJpZW5kcywgeW91IGhhdmUgdG8gZW5zdXJlIHRoYXQgd2hhdCB5b3UgYXJlIHNheWluZyBpcyBjbGVhciBhbmQgY29uY2lzZS4gTWFzdGVyIHRoZSBzY2llbmNlIG9mIHNtYXJ0IGNvbW11bmljYXRpb24gYnkgZm9jdXNpbmcgdGhlIGZvdXIgcG93ZXIgc2tpbGxzIGluIHRoZSBzZXJpZXMgVGhlIFBvd2VyIG9mIFNtYXJ0IEN1c3RvbWVyIFJlbGF0aW9ucyB0byBzdGFydCBjb25uZWN0aW5nIHdpdGggbW9yZSBwZW9wbGUgYW5kIGJ1aWxkIGxvbmcgdGVybSBzdWNjZXNmdWxsIHJlbGF0aW9ucy48L3A+DQo8cD7CoMKgwqDCoMKgIFRoaXMgdHJhaW5pbmcgc2VyaWVzIHdpbGwgcHJvdmlkZTs8L3A+DQo8dWw+DQo8bGk+VGhlIHBvd2VyIG9mIHVzaW5nIG1pY3JvLW1vbWVudHMgdG8geW91ciBhZHZhbnRhZ2U8L2xpPg0KPGxpPkEgZGVlcCB1bmRlcnN0YW5kaW5nIG9uIHRoZSBzY2llbmNlIGFuZCB0aGUgYXJ0IG9mIGhvdyBwZW9wbGUgdmlldyB5b3U8L2xpPg0KPGxpPlRlY2huaXF1ZXMgdG8gZW5oYW5jZSB5b3VyIGxpc3RlbmluZyBza2lsbHM8L2xpPg0KPGxpPlRoZSBpbXBvcnRhbmNlIG9mIGFza2luZyBzbWFydCBxdWVzdGlvbnMgbGVhZGluZyB0byBlbmhhbmNlZCBncm93dGggaW4geW91ciBidXNpbmVzczwvbGk+DQo8L3VsPmQCAw8VAgM3NDYlVGhlLVBvd2VyLW9mLVNtYXJ0LUN1c3RvbWVyLVJlbGF0aW9uc2QCBQ8WAh8ABQU2MC4wMGQCBQ9kFgpmDw8WAh8DBUtodHRwczovL3d3dy5sZWFybmVhcm5vd24uY29tL2Fzc2V0cy9JbWFnZXMvUHJvZHVjdEltYWdlcy84NjFfbWVkaXVtLmpwZz92PTJkZAIBDxYCHwAFCUdvbGQgUGFja2QCAg8WAh8ABf0FVGhlIExFTyAxMiBNb250aCBHb2xkIFBhY2sgYWltcyB0byBpbnRyb2R1Y2UgeW91IHRvIHRoZSBiZW5lZml0cyBvZiBhY3F1aXJpbmcgZ29sZCBhc3NldHMgdGhyb3VnaCBvd25pbmcgMTBnIG9mIDk5OS45IGdvbGQuICBFeGNpdGluZyBhZGRpdGlvbnMgdG8gdGhlIExFTyAxMiBNb250aCBHb2xkIFBhY2sgaXMgYSBMaW1pdGVkLUVkaXRpb24gQ29sbGVjdG9y4oCZcyBJdGVtIERpc2NvdW50IENhcmQgYXMgd2VsbCBhcyAxMCDCozEwMCBEaXNjb3VudCBjYXJkcyB0byBlbnRpY2Ugb3RoZXIgbWVtYmVycyB0byBwdXJjaGFzZSBhIDEyIE1vbnRoIExFTyBHb2xkIFBhY2suICA8YnIgLz4gPGJyIC8+QXMgd2VsbCBhcyB0aGUgZ29sZCB0aGVyZSB3aWxsIGJlIGFjY2VzcyB0byBMRU8gQ29yZUxpbmUgYW5kIExFTyBTa2lsbHMgQ291cnNlcyBmb3IgeW91ciBjaG9zZW4gc3Vic2NyaXB0aW9uIHBlcmlvZC4gWW91IHdpbGwgYWxzbyByZWNlaXZlIDQgVklQIExpdmUgU2VtaW5hciB0aWNrZXRzIHdoaWNoIHdpbGwgcHJvdmlkZSB5b3Ugd2l0aCB0aGUgb3Bwb3J0dW5pdHkgdG8gYXR0ZW5kIGR5bmFtaWMgTGl2ZSBTZW1pbmFyIHRyYWluaW5ncyB3aXRoIHRvcC10aWVyIHRyYWluZXJzLiA8Yj5WSVAgTGl2ZSBTZW1pbmFyIFRpY2tldHMgaW5jbHVkZSBwcmlvcml0eSBzZWF0aW5nIGF0IHRoZSBldmVudCBhbmQgYm9udXMgdHJhaW5pbmcgc2Vzc2lvbnMgYXMgd2VsbCBhcyBsdW5jaCBvciBkaW5uZXIgd2l0aCB0aGUgU2VtaW5hciB0cmFpbmVycy48L2I+ZAIDDxUCAzg2MQlHb2xkLVBhY2tkAgUPFgIfAAUIMiwwMDAuMDBkAhMPFgIfAQIIFhBmD2QWCGYPFQIBORYxNTIwMjM1ODMwX3RyYWluZXIucG5nZAIBDxYCHwAFDUphY2tpZSBKYXJ2aXNkAgMPFgIfAAWQCkphY2tpZSBKYXJ2aXMsIGF1dGhvciBvZiBRdWljayBXaW5zIGluIFNhbGVzIGFuZCBNYXJrZXRpbmcsIGlzIGEgVUsgYmFzZWQgc2FsZXMgYW5kIGJ1c2luZXNzIGRldmVsb3BtZW50IGV4cGVydC4gU2hlIGlzIGEgYnVzaW5lc3Mgb3duZXIsIG1lbnRvciBhbmQgY29hY2ggdG8gQW1iaXRpb3VzIFNNRXMgYnVzaW5lc3Mgb3duZXJzIGhlbHBpbmcgdGhlbSB0byB3aW4gdGhlIGNsaWVudHMgdGhleSBhc3BpcmUgdG8gaW4gYW4gJmxzcXVvO2F1dGhlbnRpYyZyc3F1bzsgbWFubmVyLiBIZXIgcGFzc2lvbiBoYXMgYWx3YXlzIGJlZW4gaW4gaGVscGluZyBwZW9wbGUgdG8gZ3JvdywgdGhyb3VnaCBpbnNwaXJpbmcgaWRlYXMgY291cGxlZCB3aXRoIHByYWN0aWNhbCB3YXlzIHRvIGFjaGlldmUgcmVzdWx0cyBpbiB0aGUgcmVhbCB3b3JsZC4gSmFja2llIGhhcyBhIHdlYWx0aCBvZiBleHBlcmllbmNlIGdhaW5lZCBib3RoIGluIHRoZSBjb3Jwb3JhdGUgYW5kIFNNRSBlbnZpcm9ubWVudHMuIEhlciBiYWNrIGdyb3VuZCBpbmNsdWRlcyBiZWluZyBhbiBhd2FyZCB3aW5uaW5nIHNhbGVzIGFjaGlldmVyLCBhIG1vdGl2YXRpb25hbCBzYWxlcyBtYW5hZ2VyIGFuZCBhIHRyYWluaW5nIG1hbmFnZXIgcmVzcG9uc2libGUgZm9yIHNldHRpbmcgdXAgYSBuYXRpb25hbCB0cmFpbmluZyBjZW50cmUgZm9yIG9uZSBvZiB0aGUgVUsmcnNxdW87cyBsYXJnZXN0IG1lZGlhIGdyb3Vwcy4gSGVyIHRyYWluaW5nIGJ1c2luZXNzIGFsc28gc2VydmVkIHNvbWUgb2YgdGhlIGJlc3Qga25vd24gcmV0YWlsZXJzLCBwcm9mZXNzaW9uYWwgc2VydmljZSBmaXJtcywgYmFua3MsIGFuZCB0b3AgdGllciBvcmdhbmlzYXRpb25zIGluIHRoZSBVSy4gU2hlIGlzIGEgbWFzdGVyIHByYWN0aXRpb25lciBvZiBOTFAgYW5kIGEgbWVtYmVyIG9mIHRoZSBwcm9mZXNzaW9uYWwgaW5zdGl0dXRlIG9mIHNhbGVzIGFuZCBtYXJrZXRpbmcgbWFuYWdlbWVudC4gU2hlIGlzIGN1cnJlbnRseSBncm93aW5nIGhlciBvd24gU01FIGJ1c2luZXNzICZsc3F1bztIZWFydCBvZiBidXNpbmVzcyZyc3F1bzsgaW4gdGhlIFVLLCB0aGF0IGJyaW5ncyB0b2dldGhlciBhIHRlYW0gb2YgbGlrZS1taW5kZWQgYnVzaW5lc3MgbWVudG9ycyBhbmQgcHJvZmVzc2lvbmFsIHNlcnZpY2UgcHJvdmlkZXJzIGFsbCB3aG8gc2hhcmUgdGhlIGRlc2lyZSB0byBtYWtlIGEgZGlmZmVyZW5jZSB0aHJvdWdoIHRoZSB3b3JrIHRoZXkgZG8uIEphY2tpZSB3b3VsZCBsaWtlIHRvIGhlbHAgeW91IHRvIHdpbiB0aGUgY2xpZW50cyB5b3UgYXNwaXJlIHRvLmQCBA8VAQE5ZAIBD2QWCGYPFQICMTUkMTQzMTYxMDA4NV9KVUxJQU5fQk9MU1RFUl9waWMyMDAuanBnZAIBDxYCHwAFDkp1bGlhbiBCb2xzdGVyZAIDDxYCHwAF0wlKdWxpYW4gQm9sc3RlciBpcyBhIGdsb2JhbGx5IHJlY29nbml6ZWQgTWFzdGVyIENvYWNoIG9uIGxlYWRlcnNoaXAgYW5kIGJ1c2luZXNzIHN1Y2Nlc3MgYW5kIHdvcmtzIHdpdGggaHVuZHJlZHMgb2YgY29tcGFuaWVzIGFuZCBpbmRpdmlkdWFscyBhY3Jvc3MgTm9ydGggQW1lcmljYSB0byBkZXZlbG9wIGxlYWRlcnNoaXAgYXQgZXZlcnkgbGV2ZWwgb2YgdGhlaXIgY2FyZWVyIGFuZCBwZXJzb25hbCBzdWNjZXNzLiAmbmJzcDsgQSBzdWNjZXNzZnVsIHNlcmlhbCBlbnRyZXByZW5ldXIgd2l0aCBmaXZlIGJ1c2luZXNzZXMgdG8gZGF0ZSwgSnVsaWFuIGhhcyBtYWRlIGl0IGhpcyBtaXNzaW9uIHRvIHNoYXJlIGhpcyBrbm93bGVkZ2UgYW5kIG1vdGl2YXRlIG90aGVycyB0byBhY2hpZXZlIG1lYXN1cmFibGUgYW5kIG1lYW5pbmdmdWwgc3VjY2VzcyBhdCBib3RoIHRoZSBwZXJzb25hbCBhbmQgcHJvZmVzc2lvbmFsIGxldmVscy4gQSByZW1hcmthYmxlIHNwZWFrZXIgYW5kIGF1dGhvciwgSnVsaWFuIGhhcyBiZWVuIGZlYXR1cmVkIGFzIGd1ZXN0IGV4cGVydCBvbiBCQkMgV29ybGQgTmV3cywgU2xpY2UgVFYsIGFuZCB3b3JrcyB3aXRoIGxlYWRlcnMsIHBvbGl0aWNpYW5zIGFuZCBjZWxlYnJpdGllcyBhcm91bmQgdGhlIHdvcmxkLiBJbiAyMDEyLCBoZSBoYWQgdGhlIG9wcG9ydHVuaXR5IHRvIGNvLWF1dGhvciBhbG9uZ3NpZGUgRGVlcGFrIENob3ByYSBhbmQgRHIuIEtlbiBCbGFuY2hhcmQgKFRoZSBPbmUtTWludXRlIE1hbmFnZXIpIGFuZCBpcyBjdXJyZW50bHkgd29ya2luZyBvbiBoaXMgc2Vjb25kIGJvb2ssIHRlbnRhdGl2ZWx5IGVudGl0bGVkLCBNYXNjdWxpbml0eSBDcmlzaXM6IEJ1aWxkaW5nIExlYWRlcnNoaXAgaW50byBDb21tdW5pdHkgYW5kIENvcnBvcmF0ZSBGYWJyaWMuIEFzIGEgdGhvdWdodCBsZWFkZXIsIEp1bGlhbiBpcyBhIHBpb25lZXIgd2hvIHBvc3Nlc3NlcyB0aGUgYWJpbGl0eSB0byB0YWtlIGhpcyBtZXNzYWdlIG9mIGxlYWRlcnNoaXAgZnJvbSB0aGUgZXhlY3V0aXZlIGxldmVscyBvZiBjb3Jwb3JhdGUgZW50ZXJwcmlzZSB0byB0aGUgbWFyZ2luYWxpemVkIG1lbWJlcnMgb2Ygb3VyIHNvY2lldHkuJm5ic3A7IEhlIGJlbGlldmVzIGxlYWRlcnNoaXAgaXMgYXQgdGhlIGNvcm5lcnN0b25lIG9mIGVtcG93ZXJtZW50IGFuZCBwbGF5cyBhcyBhIHZpdGFsIHJvbGUgaW4gaG93IHdlIGRlZmluZSBhbmQgc2hhcGUgb3VyIGNvbW11bml0aWVzLmQCBA8VAQIxNWQCAg9kFghmDxUCAjM0IDE0MzY5MTk0OTNfVGF5bGFfMTc2LXgtMjAwcHguanBnZAIBDxYCHwAFDVRheWxhIEdvb2RtYW5kAgMPFgIfAAXkAyJIYXZpbmcgc3BlbnQgbWFueSB5ZWFycyB3b3JraW5nIGluIHRoZSBmaWVsZCBvZiByZXNlYXJjaCwgbWFuYWdlbWVudCwgcmVjcnVpdG1lbnQgYW5kIHRyYWluaW5nIFRheWxhIEdvb2RtYW4gaGFzIGdhdGhlcmVkIGV4dGVuc2l2ZSBrbm93bGVkZ2UgYWJvdXQgdGhlIG1vdGl2YXRpb24gb2YgcGVvcGxlIGFuZCB0aGUgc3RyYXRlZ2llcyB0aGF0IHRoZXkgdXNlLiBVc2luZyBoZXIgYmVoYXZpb3VyYWwgYWNjcmVkaXRhdGlvbnMgYW5kIGV4cGVyaWVuY2Ugb2YgcXVhbGlmaWNhdGlvbnMsIHNoZSBoYXMgY3JlYXRlZCBuZXcgd2F5cyBmb3IgZW50cmVwcmVuZXVycyB0byBhY2hpZXZlIHN1Y2Nlc3MuIEhlciBtYWluIGFpbSBpcyB0byBpbXByb3ZlIHRoZSBjdXN0b21lciBleHBlcmllbmNlLCByYWlzZSB0aGUgYnJhbmQgaWRlbnRpdHkgb2Ygc2tpbGxzIGFuZCBoZWxwIHBlb3BsZSB0byByZWFsaXplIHRoZWlyIGRldmVsb3BtZW50IHBvdGVudGlhbC5kAgQPFQECMzRkAgMPZBYIZg8VAgIzNiExNDM5ODM2NjU2X0RyLVRvbSBwcm9maWxlIHBpYy5wbmdkAgEPFgIfAAUPRHIuIFRvbSBCYXJyZXR0ZAIDDxYCHwAF2QNEci4gQmFycmV0dCBpcyBhIGhpZ2gtcHJvZmlsZSBsZWFkZXJzaGlwIGFuZCBjb21tdW5pY2F0aW9ucyBleHBlcnQuIEhlIGhhcyB0d28gTWFzdGVycyBkZWdyZWVzIGFuZCBhIFBoRCBpbiBDbGluaWNhbCBQc3ljaG9sb2d5IGFuZCBoYXMgd29ya2VkIHdpdGggRm9ydHVuZSAyMDAgY29tcGFuaWVzLiBIZSBzcGVjaWFsaXplcyBpbiBlbW90aW9uYWwgaW50ZWxsaWdlbmNlIGFzIGl0IHJlbGF0ZXMgdG8gbGVhZGVyc2hpcCwgc21hcnQgY29tbXVuaWNhdGlvbiBhbmQgdHJhaW5pbmcgY29ycG9yYXRpb25zIGluIHVuZGVyc3RhbmRpbmcgdGhlIHBvd2VyIG9mIHNtYXJ0IGN1c3RvbWVyIHJlbGF0aW9uc2hpcHMuwqAgSGlzIGdvYWwgaW4gbGlmZSBpcyBub3QgdG8gZm9jdXMgb24gd2hhdCBoZSBoYXMgZG9uZSBpbiB0aGUgcGFzdCBidXQgdG8gaGVscCBvdGhlcnMgc2VlIHdoYXQgdGhleSBjYW4gYWNoaWV2ZSBpbiB0aGUgZnV0dXJlLmQCBA8VAQIzNmQCBA9kFghmDxUCAjM5KjE0NDI5MzgyNzZfQ29ubmllIENvcmVsaW5lIHByb2ZpbGUgcGljLmpwZ2QCAQ8WAh8ABQ5Db25uaWUgUG9kZXN0YWQCAw8WAh8ABb8DQ29ubmllIGlzIGEgZ2FtZS1jaGFuZ2luZywgcmV2ZW51ZS1idWlsZGluZywgaWRlYS1nZW5lcmF0aW5nLCByZWxhdGlvbnNoaXAtYnVpbGRpbmcgQkFMTCBPRiBGSVJFLiZuYnNwOyBTaGUgaXMgYSBIYWxsIG9mIEZhbWUga2V5bm90ZSBzcGVha2VyLCBhd2FyZCB3aW5uaW5nIGF1dGhvciBvZiBzaXggYm9va3MsIGNvbWVkaWVubmUsIGZvcm1lciByYWRpbyBhbmQgVFYgcGVyc29uYWxpdHksIGFuZCB3aGF0IHdlIGNvdWxkIGFsbCB1c2Ugbm93IGFuZCB0aGVuIC0tIGEgdGhlcmFwaXN0LiZuYnNwOyBGb3IgbW9yZSB0aGFuIDI1IHllYXJzLCB0d28gbWlsbGlvbiBwZW9wbGUgYW5kIDEsMDAwIG9yZ2FuaXphdGlvbnMsIENvbm5pZSBoYXMgYmVlbiB0aGUgb25lIHRoZXkidmUgdHVybmVkIHRvIGZvciB0aGUgYW5zd2VycyB0aGV5IG5lZWQgdG8gbGl2ZSB0aGUgbGlmZSB0aGV5IHdhbnQuZAIEDxUBAjM5ZAIFD2QWCGYPFQICNDMWMTUyMDIzODg4Ml90cmFpbmVyLnBuZ2QCAQ8WAh8ABQ5CcmFuY28gSmV1bmVzc2QCAw8WAh8ABYsFQnJhbmNvIEpldW5lc3MsIGludGVybmF0aW9uYWwgdHJhaW5lciAmYW1wOyBjb2FjaCwgaXMgZnJvbSB0aGUgYmVhdXRpZnVsIGNvdW50cnkgU2xvdmVuaWEsIGx5aW5nIGluIHRoZSBoZWFydCBvZiBFdXJvcGUuIEhlIHN0YXJ0ZWQgaGlzIHNhbGVzIGFuZCBwcmVzZW50YXRpb24gY2FyZWVyIGF0IG9ubHkgMTkgeWVhcnMsIGFuZCBoYXMgc2luY2Ugd29ya2VkIGluIGFuZCBmb3IgbW9yZSB0aGFuIDIwMCBjb21wYW5pZXMuJm5ic3A7IEJyYW5jbyB3YXMgYSBwcm9mZXNzb3IgZm9yIDcgeWVhcnMgYXQgdGhlIEZhY3VsdHkgb2YgQnVzaW5lc3MgYW5kIEVjb25vbWljcyBpbiBTbG92ZW5pYSwgYmVjYW1lIGFuJm5ic3A7IGFjY3JlZGl0ZWQgaW50ZXJuYXRpb25hbCB0cmFpbmVyIHdpdGggZXhjZWxsZW5jZSBpbiAyMDA1LCBlbmFibGluZyBoaXMgZ2xvYmFsIGNhcmVlci4gSGUgc3BlbmRzIG1vc3QgaGlzIHRpbWUgY29hY2hpbmcgYW5kIHRyYWluaW5nIGxlYWRlcnMsIG1hbmFnZXJzIGFuZCBzYWxlcyBwcm9mZXNzaW9uYWxzIGluIGNvbXBhbmllcyZuYnNwOyByYW5naW5nIGluIHNpemUgZnJvbSA1MCB0byAxMC4wMDAgZW1wbG95ZWVzLiBCcmFuY28gYWxzbyBtYW5hZ2VzIGhpcyBvd24gY29tcGFueSB3aXRoIGEgdGVhbSBvZiAxMiBwZW9wbGUuZAIEDxUBAjQzZAIGD2QWCGYPFQICNDUWMTUyMDMxODQ1MV90cmFpbmVyLnBuZ2QCAQ8WAh8ABQ5FcmljIE1hdGhpYXNpbmQCAw8WAh8ABZwGRXJpYyBNYXRoaWFzaW4gaXMgYSBjZXJ0aWZpZWQgTWFzdGVyIFRyYWluZXIgaW4gTmV1cm8gTGluZ3Vpc3RpYyBQcm9ncmFtbWluZyAoTkxQKS4gSGUgaXMgYSBjb2FjaCwgdGhlcmFwaXN0IGFuZCBleHBlcmllbmNlZCBmYWNpbGl0YXRvciB3b3JraW5nIHdpdGggdmFyaW91cyBhdWRpZW5jZXMsIGJvdGggaW4gdGhlIHByaXZhdGUgYW5kIHByby1mZXNzaW9uYWwgYXJlbmEsIHdobyBhcmUgZW5nYWdlZCBpbiBhIHBlcnNvbmFsIGRldmVsb3BtZW50IG9yIHRoZXJhcGV1dGljIGFwcHJvYWNoLiBIZSBjcmVhdGVkIHRoZSBmaXJzdCBhdXRob3JpemVkIHRyYWluaW5nIGluc3RpdHV0ZSBpbiB0aGUgRnJlbmNoIFdlc3QgSW5kaWVzLCBkZWRpY2F0ZWQgdG8gdGhlIHRyYWluaW5nIG9mIHByb2Zlcy1zaW9uYWxzIHdvcmtpbmcgaW4gdGhlIGZpZWxkIG9mIGhlbHBpbmcgYW5kIHRoZXJhcGV1dGljIGFsbGlhbmNlcyB3aXRoIHRoZWlyIHBhdGllbnRzLiBFcmljIE1hdGhpYXNpbiBoYXMgdHJhaW5lZCBudW1lcm91cyB0aGVyYXBpc3RzIGluIHRoZSB1c2Ugb2YgdGhlc2Ugc2ltcGxlIHRvbGxzIHRoYXQgY2FuIGVhc2lseSBpbXByb3ZlIHRoZWlyIHBhLXRpZW50cyIgZGFpbHkgbGl2ZXM6IHBzeWNob2xvZ2lzdHMsIGNvYWNoZXMsIHNvY2lhbCB3b3JrZXJzLCBoZWFsdGggcHJvZmVzc2lvbmFscyBoYXZlIHVzZWQgdGhlc2UgdG9vbHMgc3VjY2Vzc2Z1bGx5IGZvciBkZXByZXNzaW9uLCBwaG9iaWFzLCB0cmF1bWFzLCBhZGRpY3Rpb24sIGVhdGluZyBkaXNvcmRlcnMsIHN0cmVzcyBiZWZvcmUgYW4gZXhhbWQCBA8VAQI0NWQCBw9kFghmDxUCAjQ5FjE1MjAzMTg0MDVfdHJhaW5lci5wbmdkAgEPFgIfAAUQRnLDqWTDqXJpYyBBcnJvbmQCAw8WAh8ABccCRnImZWFjdXRlO2QmZWFjdXRlO3JpYyBBcnJvbiBpcyBhIHByb2Zlc3Npb25hbCBhbmQgcGVyc29uYWwgZGV2ZWxvcG1lbnQgY29hY2guIEhlIGlzIHRoZSBhdXRob3Igb2Ygc2V2ZXJhbCBib29rcyBvbiBwZXJzb25hbCBmdWxmaWxtZW50IGFuZCBzdWNjZXNzLiBIZSBoZWxwcyBoaXMgY2xpZW50cyB0cmFuc2Zvcm0gdGhlaXIgbGl2ZXMgYW5kIGdldCB3aGF0IHRoZXkgcmVhbGx5IHdhbnQuIEhpcyB1bmlxdWUgYXBwcm9hY2ggd2lsbCBhbGxvdyB5b3UgdG8gYWNoaWV2ZSBmYXN0IHJlc3VsdHMgd2l0aCBtaW5pbWFsIGVmZm9ydC4gUHJlcGFyZSB0byBiZSBzdXJwcmlzZWQhZAIEDxUBAjQ5ZAIdDxYCHwFmZBgBBR5fX0NvbnRyb2xzUmVxdWlyZVBvc3RCYWNrS2V5X18WAQUTY3RsMDAkY2hrUmVtZW1iZXJNZZUrauh4njizodrNVx5/jKdRoubvfSQEZw2OlS2ghCaj"
                            + "&__VIEWSTATEGENERATOR=CA0B0334"
                            + "&__EVENTVALIDATION=/wEdAAq/8b/Xes5vOifBFOrha6Ijitw9a+kpC5hy6PX7DCLgIN3yEg90D4xD0VTL2nxlI2+3K7xQcomXsaDT+wnL40Y39aeGJ9E30o1ViXoitCUxzOlG9Wa5jWiDkRux04aSW4dQZpyJ3ZTHNWgnT455QiXCZ0Privzz4sS9+1cugEiz000/3tac5YeGLwbAe386+AKmms97+54vhfOrqLvDxmcRyopCwaRMDR+gKCXwnhfYKgpRlQ+dVw+V2yXwaGtjE6Q="
                            + "&ctl00$txtUsername_value=" + userArr[0]
                            + "&ctl00$txtPassword_value=" + userArr[1];
            Map<String, String> map2 = new HashMap<>();
            String s = sendPostRequest(reqURL, sendData, cookie, true, null, null, map2);
//        logger.error("step-2:返回值，"+s.substring(0,100));
            if (s!=null && s.indexOf("Object moved to") < 0) {
                LeoMessage leoMessage = new LeoMessage();
                leoMessage.setMsg("密码错误");
                leoMessage.setLoginError(true);
                return leoMessage;
            }

            logger.warn("step-3,访问Leo平台，获取Etoken");
            String urlForStep3_1 = "https://www.learnearnown.com/Backoffice/LEOcoinPlatform.aspx";
            Map<String, String> map3_1 = new HashMap<>();
            String htmlForStep3_1 = getReponseStringForStep3(urlForStep3_1, cookie, map3_1);

            String EToken = "";
            Pattern pattern = Pattern.compile("name=\"EToken\" value=\"([\\S]*)\"");
            Matcher matcher = pattern.matcher(htmlForStep3_1);
            if (matcher.find()) {
                EToken = matcher.group(1);
            }
            logger.warn("step-3,返回值：" + EToken);

            logger.warn("step-4,用Etoken使cookie在leo平台生效");
            String urlForStep4 = "https://www.platform.leocoin.org/Authentication.aspx";
            String sendDataForStep4 = "EToken=" + EToken;
            Map<String, String> map4 = new HashMap<>();
            String s4 = sendPostRequest(urlForStep4, sendDataForStep4, cookie, true, null, null, map4);
//        logger.error("step-4:返回值："+s4);

            logger.warn("step-5,leo平台输入验证码");
            String sendDataForStep6 = "__VIEWSTATE=/wEPDwUKMTIyNjE2NTc0NWRkq0vAtrZufxJRxDI0GAMwS+ShEt4="
                    + "&__VIEWSTATEGENERATOR=19A82BBE"
                    + "&__EVENTVALIDATION=/wEWBALZh5GQDQKy88z7BwKOxfX2BQKV5d6EAzyRY4b92Dh/JgORfk5gIr3Cf2Op" +
                    "&ctl00$ContentPlaceHolder1$txtVerificationCode_value=" + userArr[2] +
                    "&ctl00$ContentPlaceHolder1$btnVerify=Verify";
            String urlForStep6 = "https://www.platform.leocoin.org/VerificationCode.aspx";
            Map<String, String> map6 = new HashMap<>();
            String s5 = sendPostRequest(urlForStep6, sendDataForStep6, cookie, true, null, null, map6);
            LeoMessage leoMessage = new LeoMessage();

            leoMessage.setCookie(cookie);
            if(s5 ==null){
                leoMessage.setMsg("登录失败：连接不到卖币平台，请稍后再试！");
                leoMessage.setLoginError(true);
            }else if (s5.indexOf("Invalid Verification Code") > 0) {
                leoMessage.setMsg("验证码错误！");
                leoMessage.setLoginError(true);
            }else {
                leoMessage.setMsg(cookie);
                logger.error("登录成功"+leoMessage);
            }

            return leoMessage;
        } catch (Exception e) {
            logger.error(e.getMessage(), e);
        }
        LeoMessage leoMessage = new LeoMessage();
        leoMessage.setMsg("登录错误：可能是网站连接比较慢。");
        leoMessage.setLoginError(true);
        return leoMessage;
    }


    public boolean getCode(String cookie){
        String sendDataForStep6 = "__VIEWSTATE=/wEPDwUKMTIyNjE2NTc0NWRkq0vAtrZufxJRxDI0GAMwS+ShEt4="
                + "&__VIEWSTATEGENERATOR=19A82BBE"
                + "&__EVENTVALIDATION=/wEWBALZh5GQDQKy88z7BwKOxfX2BQKV5d6EAzyRY4b92Dh/JgORfk5gIr3Cf2Op" +
                "ctl00$ContentPlaceHolder1$txtVerificationCode_value="+
                "ctl00$ContentPlaceHolder1$btnVerificationCode=Get Code";
        String urlForStep6 = "https://www.platform.leocoin.org/VerificationCode.aspx";
        Map<String, String> map6 = new HashMap<>();
        String s5 = sendPostRequest(urlForStep6, sendDataForStep6, cookie, true, null, null, map6);
        // Your verification code has been sent to your mobile and email address
        return true;
    }

    @Override
    public List<NamePwdCookie> getCookies(List<NamePwdCookie> requestNames) {
        CountDownLatch latch = new CountDownLatch(requestNames.size());
        List<NamePwdCookie> namePwdCookieList = new ArrayList<>();
        LeoUser currentLoginUser = UserThreadUtil.getLeoUser();
        for (NamePwdCookie user : requestNames) {
            Thread thread = new Thread(new GetCookiesThread(currentLoginUser,this, latch, user));
            namePwdCookieList.add(user);
            user.setLoginError(true);
            thread.start();
        }
        return namePwdCookieList;
    }

    @Override
    public List<OrderDetail> getOrders(String cookie) {
        for(int i=0;i<3;i++){
            String reqURL = "https://www.platform.leocoin.org/CustomerOrderHistory.aspx?Type=Sell&PageID=1";
            Map<String, String> reponseMap = getCookieReponseString(reqURL, cookie);
            String reponseHtml = reponseMap.get("reponseHtml");
            List<OrderDetail> orders =  getOrderDetailFromHtml(reponseHtml);
            if(orders.size()>0){
                return orders;
            }
        }
        return new ArrayList<>();
    }

    @Override
    public OrderDetail cancelOrder(OrderDetail orderDetail) {
        String reqURL = "https://www.platform.leocoin.org/cancelSellOrder.aspx?Id=" + orderDetail.getId();

        String sendDataForStep6 = "__VIEWSTATE=/wEPDwULLTExOTc2NzMzMzkPZBYCZg9kFgICAw9kFgICAQ9kFgICAQ9kFgoCAw8WAh4EVGV4dAUBMGQCCQ9kFgICAQ8WAh8AZWQCCw9kFgICAQ8WAh8AZWQCDQ9kFgICAQ8WAh8AZWQCFQ8QZGQWAGRkQ6neP72HoAqi41zUqYFFvZY7csY="
                + "&__VIEWSTATEGENERATOR=1C0F98BC"
                + "&__EVENTVALIDATION=/wEWAgLZ5+HBBQKrlNGpBtzBaAkuCf0UNbFWvEAfHqkfpC8i"
                + "&ctl00$ContentPlaceHolder1$btnConfirm=Confirm";

        Map<String, String> map6 = new HashMap<>();
        String s5 = sendCancelPostRequest(reqURL, sendDataForStep6, orderDetail.getCookie(), true, null, null, map6);
        if(StringUtils.hasText(s5)){
            orderDetail.setCancelSuccess(true);
        }
        return orderDetail;
    }

    @Override
    public List<OrderDetail> cancelOrders(List<OrderDetail> orderDetails) {
        CountDownLatch latch = new CountDownLatch(orderDetails.size());
        List<OrderDetail> namePwdCookieList = new ArrayList<>();

        LeoUser currentLoginUser = UserThreadUtil.getLeoUser();

        for (OrderDetail user : orderDetails) {

            namePwdCookieList.add(user);
            Thread thread = new Thread(new CancleOrderThread(currentLoginUser,this, latch, user));
            thread.start();
        }
//        try {
//            latch.await();
//        } catch (InterruptedException e) {
//            e.printStackTrace();
//        }

        return namePwdCookieList;
    }

    public static void main(String[] args) {

//        String r = getCookieForStep6("BNES_ASP.NET_SessionId=6zld2iaP89h\\MBqQlp5lcioJyYQVxZQX/DcJJEX9Y3QK3sYFp5CVShHVuDNFqMMp/0uTcuagFGpsxoEb2Mt9tetRveg/7G7zsVM6bHMdOyPt6944S7ZCVRA==;ASP.NET_SessionId=pce3jl45ms12m2iroa1mde45;");
//        LeoMessage r = new LeoServiceImpl().getCookie("");
//        logger.debug(r.getMsg());
//        List<NamePwdCookie> cookies = new LeoServiceImpl().getCookies("ldd0601 Leo170730776* da422d$hsx0601 Leo170730776* 3c27b8");
//        for(NamePwdCookie cookie:cookies){
//            logger.debug("name:"+cookie.getName() +" cookie:"+cookie.getCookie());
//        }
        List<OrderDetail> details = getOrderDetailFromHtml("");
        details.forEach(o -> logger.debug(o));
    }

    private static List<OrderDetail> getOrderDetailFromHtml(String html) {

        Pattern pattern = Pattern.compile("<tr class='(?:Canceled|Active|Expired|Complete)+'>([\\S|\\s]*?)<\\/tr>");
        Matcher matcher = pattern.matcher(html);
        List<OrderDetail> orderDetails = new ArrayList<>();
        while (matcher.find()) {
            String tr = matcher.group(1);
            Pattern patternTd = Pattern.compile("<td class=\"(.)*?\">([\\S|\\s]*?)<\\/td>");
            Matcher matcher2 = patternTd.matcher(tr);
            int i = 1;
            OrderDetail detail = new OrderDetail();
            while (matcher2.find()) {
                String value = matcher2.group(2);
                if (i == 1) {
                    detail.setOrderType(matcher2.group(2));
                } else if (i == 2) {
                    detail.setVolume(value);
                } else if (i == 3) {
                    detail.setPrice(value);
                } else if (i == 4) {
                    detail.setCost(value);
                } else if (i == 5) {
                    if(value!=null){
                        value = value.replaceAll("Mar","三月");
                    }
                    detail.setDateTime(value);
                } else if (i == 6) {
                    if(value!=null && value.trim().equals("Canceled")){
                        value = "已取消";
                    }else if(value!=null && value.trim().equals("Active")){
                        value = "挂单中";
                    }else if(value!=null && value.trim().equals("Expired")){
                        value = "已过期";
                    }else if(value!=null && value.trim().equals("Complete")){
                        value = "成功出售";
                    }

                    detail.setStatus(value);
                } else if (i == 7) {
                    if (value.indexOf("Id=") > 0) {
                        detail.setId(value.substring(value.indexOf("Id=") + 3, value.indexOf("\">")));
                    }
                } else {

                }
                i++;
            }
            orderDetails.add(detail);
        }
        return orderDetails;
    }


    private String getReponseStringForStep3(String url, String cookie, Map<String, String> map2) {
        Map<String, String> map = new HashMap<>();
        String result = "";
        HttpURLConnection conn;
        URL realUrl = null;
        try {
            realUrl = new URL(url);

            conn = (HttpURLConnection) realUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.setUseCaches(false);
            conn.setReadTimeout(300000);
            conn.setConnectTimeout(300000);
            conn.setInstanceFollowRedirects(false);
            conn.setRequestProperty("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
            conn.setRequestProperty("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
            conn.setRequestProperty("Cache-Control", "max-age=0");
            conn.setRequestProperty("Connection", "keep-alive");
            conn.setRequestProperty("Host", "www.learnearnown.com");
            conn.setRequestProperty("Referer", "http://www.learnearnown.com/");
            conn.setRequestProperty("Upgrade-Insecure-Requests", "1");
            conn.setRequestProperty("Cookie", cookie);
            conn.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
            try {
                int code = conn.getResponseCode();
                conn.getResponseMessage();
                if (code == 200 || code == 302) {
                    List<String> list = conn.getHeaderFields().get("Set-Cookie");

                    InputStream is = conn.getInputStream();
                    BufferedReader in = new BufferedReader(new InputStreamReader(is, "UTF-8"));
                    StringBuffer buffer = new StringBuffer();
                    String line = "";
                    while ((line = in.readLine()) != null) {
                        buffer.append(line);
                    }
                    result = buffer.toString();
                    if (map2 != null) {
                        if (map2 != null) {
//                            getResponseHeader(map2, response);
//                            getParamsFromHtml(map2,result);
                        }
                    }
                    in.close();
                    is.close();
                }
            } catch (Exception e) {
                logger.debug(" - error: " + e);
            } finally {
                conn.disconnect();
            }
            map.put("reponseHtml", result);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return map.get("reponseHtml");
    }


    private Map<String, String> getReponseString(String url) {
        Map<String,String> requestHeader = new HashMap<>();

        requestHeader.put("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
        requestHeader.put("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
        requestHeader.put("Cache-Control", "max-age=0");
        requestHeader.put("Connection", "keep-alive");
        requestHeader.put("Host", "www.platform.leocoin.org");
        requestHeader.put("Referer", "http://www.learnearnown.com/");
        requestHeader.put("Upgrade-Insecure-Requests", "1");
        requestHeader.put("User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");


        String resultHtml = HttpClientUtil.sendGetRequest(url,requestHeader);



        Map<String, String> map = new HashMap<>();
        String result = "";
        HttpURLConnection conn;
        URL realUrl = null;
        try {
            realUrl = new URL(url);

            conn = (HttpURLConnection) realUrl.openConnection();
            conn.setRequestMethod("GET");
            conn.setUseCaches(false);
            conn.setReadTimeout(300000);
            conn.setConnectTimeout(300000);
            conn.setInstanceFollowRedirects(true);
            conn.setRequestProperty("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
            conn.setRequestProperty("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
            conn.setRequestProperty("Cache-Control", "max-age=0");
            conn.setRequestProperty("Connection", "keep-alive");
            conn.setRequestProperty("Host", "www.platform.leocoin.org");
            conn.setRequestProperty("Referer", "http://www.learnearnown.com/");
            conn.setRequestProperty("Upgrade-Insecure-Requests", "1");
            conn.setRequestProperty("User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
            try {
                int code = conn.getResponseCode();
                conn.getResponseMessage();
                if (code == 200) {
                    List<String> list = conn.getHeaderFields().get("Set-Cookie");
                    map.put("cookie", list.get(0).substring(0, list.get(0).indexOf(";") + 1));
                    InputStream is = conn.getInputStream();
                    BufferedReader in = new BufferedReader(new InputStreamReader(is, "UTF-8"));
                    StringBuffer buffer = new StringBuffer();
                    String line = "";
                    while ((line = in.readLine()) != null) {
                        buffer.append(line);
                    }
                    result = buffer.toString();

                    in.close();
                    is.close();
                }
            } catch (Exception e) {
                logger.debug(" - error: " + e);
            } finally {
                conn.disconnect();
            }
            map.put("reponseHtml", result);
        } catch (Exception e) {
            logger.error("", e);
        }
        return map;
    }

    private Map<String, String> getCookieReponseString(String url, String cookie) {
        Map<String,String> requestHeader = new HashMap<>();
        requestHeader.put("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
        requestHeader.put("Accept-Language", "zh-CN,zh;q=0.8,en;q=0.6");
        requestHeader.put("Cache-Control", "private, max-age=0, no-cache");
        requestHeader.put("Connection", "keep-alive");
        requestHeader.put("Host", "www.platform.leocoin.org");
        requestHeader.put("Referer", "https://www.platform.leocoin.org/Default.aspx");
        requestHeader.put("Upgrade-Insecure-Requests", "1");
        requestHeader.put("User-Agent", "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36");
        requestHeader.put("Cookie", cookie);
        String resultHtml = HttpClientUtil.sendGetRequest(url,requestHeader);
        Map<String, String> map1 = new HashMap<>();
        map1.put("reponseHtml", resultHtml);
        return map1;
    }


    /**
     * 发送HTTP_POST请求
     * <>该方法会自动关闭连接,释放资源</>
     * 当<code>isEncoder=true</code>时,其会自动对<code>sendData</code>中的[中文][|][ ]等特殊字符进行<code>URLEncoder.encode(string,encodeCharset)</code>
     *
     * @param reqURL        请求地址
     * @param sendData      请求参数,若有多个参数则应拼接成param11=value11&22=value22&33=value33的形式后,传入该参数中
     * @param isEncoder     请求数据是否需要encodeCharset编码,true为需要
     * @param encodeCharset 编码字符集,编码请求数据时用之,其为null时默认采用UTF-8解码
     * @param decodeCharset 解码字符集,解析响应数据时用之,其为null时默认采用UTF-8解码
     * @return 远程主机响应正文
     */
    public static String sendPostRequest(String reqURL, String sendData, String cookie, boolean isEncoder, String encodeCharset, String decodeCharset, Map<String, String> map2) {
        String responseContent = null;
//        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager();
        CloseableHttpClient httpClient = HttpClientSingleton.getHttpClient();
        HttpPost httpPost = new HttpPost(reqURL);

        RequestConfig requestConfig = RequestConfig.custom()
                .setConnectTimeout(600000).setConnectionRequestTimeout(6000)
                .setSocketTimeout(600000).build();
        httpPost.setConfig(requestConfig);

        httpPost.setHeader("Referer", "https://www.learnearnown.com");
        httpPost.setHeader("Accept-Language", "zh-CN,zh;q=0.9");
        httpPost.setHeader("Origin", "https://www.learnearnown.com");
        httpPost.setHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
        httpPost.setHeader("Upgrade-Insecure-Requests", "1");
        httpPost.setHeader("Content-Type", "application/x-www-form-urlencoded");
        httpPost.setHeader("Cache-Control", "max-age=0");
        httpPost.setHeader("Accept-Encoding", "gzip, deflate, br");
        httpPost.setHeader("User-Agent", "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36");
        if (!org.springframework.util.StringUtils.isEmpty(cookie)) {
            httpPost.setHeader("Cookie", cookie);
        }

        CloseableHttpResponse response = null;
        try {
            if (isEncoder) {
                List<NameValuePair> formParams = new ArrayList<NameValuePair>();
                for (String str : sendData.split("&")) {
                    formParams.add(new BasicNameValuePair(str.substring(0, str.indexOf("=")), str.substring(str.indexOf("=") + 1)));
                }
                ContentType contentType = ContentType.create("text/plain", Consts.UTF_8);
                httpPost.setEntity(new StringEntity(URLEncodedUtils.format(formParams, encodeCharset == null ? "UTF-8" : encodeCharset), contentType));
            } else {
                httpPost.setEntity(new StringEntity(sendData));
            }
            response = httpClient.execute(httpPost);
            HttpEntity entity = response.getEntity();
            if (null != entity) {
                if (entity.getContentEncoding() != null) {
                    if ("gzip".equalsIgnoreCase(entity.getContentEncoding().getValue())) {
                        entity = new GzipDecompressingEntity(entity);
                    } else if ("deflate".equalsIgnoreCase(entity.getContentEncoding().getValue())) {
                        entity = new DeflateDecompressingEntity(entity);
                    }
                }
                if (entity.getContentLength() > 2147483647L) {
                    throw new IllegalArgumentException("HTTP entity too large to be buffered in memory");
                }
                responseContent = EntityUtils.toString(entity, "UTF-8");
                if (map2 != null) {
                    getResponseHeader(map2, response);
                }
            }
        } catch (Exception e) {
            logger.error("与[" + reqURL + "]通信过程中发生异常,堆栈信息如下", e);
        } finally {
            if (response != null) {
                try {
                    response.close();
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }
        return responseContent;
    }


    public static String sendCancelPostRequest(String reqURL, String sendData, String cookie, boolean isEncoder, String encodeCharset, String decodeCharset, Map<String, String> map2) {
        String responseContent = null;
//        PoolingHttpClientConnectionManager cm = new PoolingHttpClientConnectionManager();
        CloseableHttpClient httpClient = HttpClientSingleton.getHttpClient();
        HttpPost httpPost = new HttpPost(reqURL);

        RequestConfig requestConfig = RequestConfig.custom()
                .setConnectTimeout(600000).setConnectionRequestTimeout(1000)
                .setSocketTimeout(600000).build();
        httpPost.setConfig(requestConfig);

        httpPost.setHeader("Referer", reqURL);
        httpPost.setHeader("Accept-Language", "zh-CN,zh;q=0.9");
        httpPost.setHeader("Host", "www.platform.leocoin.org");
        httpPost.setHeader("Origin", "https://www.platform.leocoin.org");
        httpPost.setHeader("Accept", "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8");
        httpPost.setHeader("Upgrade-Insecure-Requests", "1");
        httpPost.setHeader("Content-Type", "application/x-www-form-urlencoded");
        httpPost.setHeader("Cache-Control", "max-age=0");
        httpPost.setHeader("Accept-Encoding", "gzip, deflate, br");
        httpPost.setHeader("User-Agent", "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36");
        if (!org.springframework.util.StringUtils.isEmpty(cookie)) {
            httpPost.setHeader("Cookie", cookie);
        }
        try {
            if (isEncoder) {
                List<NameValuePair> formParams = new ArrayList<NameValuePair>();
                for (String str : sendData.split("&")) {
                    formParams.add(new BasicNameValuePair(str.substring(0, str.indexOf("=")), str.substring(str.indexOf("=") + 1)));
                }
                ContentType contentType = ContentType.create("text/plain", Consts.UTF_8);
                httpPost.setEntity(new StringEntity(URLEncodedUtils.format(formParams, encodeCharset == null ? "UTF-8" : encodeCharset), contentType));
            } else {
                httpPost.setEntity(new StringEntity(sendData));
            }
            HttpResponse response = httpClient.execute(httpPost);
            HttpEntity entity = response.getEntity();
            if (null != entity) {
                if (entity.getContentEncoding() != null) {
                    if ("gzip".equalsIgnoreCase(entity.getContentEncoding().getValue())) {
                        entity = new GzipDecompressingEntity(entity);
                    } else if ("deflate".equalsIgnoreCase(entity.getContentEncoding().getValue())) {
                        entity = new DeflateDecompressingEntity(entity);
                    }
                }
                if (entity.getContentLength() > 2147483647L) {
                    throw new IllegalArgumentException("HTTP entity too large to be buffered in memory");
                }
                responseContent = EntityUtils.toString(entity, "UTF-8");
                if (map2 != null) {
                    getResponseHeader(map2, response);
                }
            }
        } catch (Exception e) {
            logger.info("与[" + reqURL + "]通信过程中发生异常,堆栈信息如下", e);
        } finally {
//            httpClient.shutdown();
        }
        return responseContent;
    }

    private static void getResponseHeader(Map<String, String> map2, HttpResponse response) {
        String set_cookie = "";
        Header[] responseHeaders = response.getAllHeaders();
        for (int i = 0; i < responseHeaders.length; i++) {
            Header item = responseHeaders[i];
            if (item.getName().equals("Set-Cookie")) {
                String tempCookieItemValue = item.getValue();
                tempCookieItemValue = tempCookieItemValue.substring(0, tempCookieItemValue.indexOf(";") + 1);
                if (set_cookie == "") {
                    set_cookie = tempCookieItemValue;
                } else {
                    set_cookie += " " + tempCookieItemValue;
                }
            }
        }
        map2.put("set_cookie", set_cookie);
    }


}
